---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack | Main Master | test-cloudformation'

Parameters:
  BranchName:
    Default: BranchName
    Description: Choose which Branch do you want to use
    Type: String
  Customer:
    Description: is used as Customer tag value for all resources
    Type: String
    Default: Customer
    AllowedPattern: ^[A-Za-z0-9]*$
    ConstraintDescription: must contain only alphanumeric characters and numbers.
    MaxLength: 20
    MinLength: 1
  CustomerProject:
    Description: is used as Customer project tag value for all resources
    Type: String
    Default: CustomerProject
    AllowedPattern: ^[A-Za-z0-9]*$
    ConstraintDescription: must contain only alphanumeric characters and numbers.
    MaxLength: 20
    MinLength: 1
  Environment:
    Description: Environment to deploy. Use staging for limited resources and no alerts.
    Type: String
    Default: Staging
    AllowedValues:
    - Staging
    - Production

Mappings:

Resources:
  lambdastack:
  Type: AWS::Cloudformation::stack
  Properties:
    TemplateURL: '${MainStackURL}sub-lambda.yml'
    Parameters:
      Runtime: java8
      FunctionName: test-function
      FunctionTimeOut: 300
      MemorySize: 128

  # apigatewaystack:
  # s3bucketstack:  
  

Outputs:
  LambdaFunctionArn:
    Description: ARN of the FunctionName
    value:  !GetAtt lambdastack.Arn