---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'sub ec2 stack: ec2-intance'

InstaneType:
  Description: type of the instance
  Type: AWS::SSM::Parameter::Valsue<string>
KeyName:
  Description: key of the instance
  Type: AWS::SSM::Parameter::Value<AWS:EC2:KeyPair:KeyName>
ImageId:
  Description: image id need to pass
  Type: AWS::SSM::Parameter::Value<AWS:EC2:Image:Ide> 
SubnetId:
  Description: image id need to pass
  Type: AWS::SSM::Parameter::Value<AWS:EC2:Subnet>    
VpcId:
  Type: AWS::SSM::Parameter::Value<AWS:EC2:VPC>
SecurityGroupId:
  Type: AWS::SSM::Parameter::Value<AWS:Ec2:SecurityGroup:Id>     
Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0c02fb55956c7d316
      InstanceType: t2-micro
      KeyName: Jenkins
      SubnetId: subnet-0691c420df320c2c1
      VpcId: vpc-0b8cab68038bbf411
      SecurityGroupIds: sg-0a024b5f851d9600b
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs: 
          VolumeType: "io1"
          Iops: "200"
          DeleteOnTermination: "false"
          VolumeSize: "20"
      - DeviceName: "/dev/sdk"
        NoDevice: {}
