---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'sub ec2 stack: ec2-intance'

InstaneType:
  Description: type of the instance
  Type: AWS::SSM::Parameter::Value<string>
KeyName:
  Description: key of the instance
  Type: AWS::SSM::Parameter::Value<AWS:EC2:KeyPair:KeyName>
ImageId:
  Description: image id need to pass
  Type: AWS::SSM::Parameter::Value<AWS:EC2:Image:Ide> 
SubnetId:
  Description: image id need to pass
  Type: AWS::SSM::Parameter::Value<AWS:EC2:Subnet>    
VpcId:
  Type: AWS::SSM::Parameter::Value<AWS:EC2:VPC>
SecurityGroupId:
  Type: AWS::SSM::Parameter::Value<AWS:Ec2:SecurityGroup:Id>     
Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ImageId
      InstaneType: !Ref InstaneType
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      VpcId: !Ref VpcId
      SecurityGroupId: !Ref SecurityGroupId
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs: 
          VolumeType: "io1"
          Iops: "200"
          DeleteOnTermination: "false"
          VolumeSize: "20"
      - DeviceName: "/dev/sdk"
        NoDevice: {}
